
-- phpMyAdmin SQL Dump
-- version 3.5.2.2
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Feb 12, 2017 at 02:38 PM
-- Server version: 10.0.28-MariaDB
-- PHP Version: 5.2.17

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `u717881434_akad`
--

-- --------------------------------------------------------

--
-- Table structure for table `books`
--

CREATE TABLE IF NOT EXISTS `books` (
  `id` int(8) NOT NULL AUTO_INCREMENT,
  `book_name` varchar(256) COLLATE utf8_unicode_ci NOT NULL,
  `book_year` year(4) NOT NULL,
  `book_author` varchar(256) COLLATE utf8_unicode_ci NOT NULL,
  `book_genre` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `book_synopsis` text COLLATE utf8_unicode_ci NOT NULL,
  `book_link` text COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=55 ;

--
-- Dumping data for table `books`
--

INSERT INTO `books` (`id`, `book_name`, `book_year`, `book_author`, `book_genre`, `book_synopsis`, `book_link`) VALUES
(1, 'The Indifferent Stars Above: The Harrowing Saga of the Donner Party', 2008, 'Daniel James Brown', 'Travel', 'From the #1 bestselling author of The Boys in the Boat comes an unforgettable epic of family, tragedy, and survival on the American frontier\r\n\r\n“An ideal pairing of talent and material.… Engrossing.… A deft and ambitious storyteller.” – Mary Roach, New York Times Book Review\r\n\r\nIn April of 1846, twenty-one-year-old Sarah Graves, intent on a better future, set out west from Illinois with her new husband, her parents, and eight siblings. Seven months later, after joining a party of pioneers led by George Donner, they reached the Sierra Nevada Mountains as the first heavy snows of the season closed the pass ahead of them. In early December, starving and desperate, Sarah and fourteen others set out for California on snowshoes, and, over the next thirty-two days, endured almost unfathomable hardships and horrors.\r\n\r\nIn this gripping narrative, New York Times bestselling author Daniel James Brown sheds new light on one of the most legendary events in American history. Following every painful footstep of Sarah’s journey with the Donner Party, Brown produces a tale both spellbinding and richly informative.', 'https://www.amazon.com/gp/product/B0026SCNDQ/ref=s9_acsd_top_hd_bw_b4Tr_c_x_1_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-6&pf_rd_r=ADJ0BD61PEAW285C5TAF&pf_rd_t=101&pf_rd_p=a1319b60-bc1c-5655-92b2-70a29978ae11&pf_rd_i=17227'),
(2, 'Maui Revealed: The Ultimate Guidebook', 2015, 'Andrew Doughty', 'Travel', 'The finest guidebook ever written for Maui. Now you can plan your best vacation--ever. This all new seventh edition is a candid, humorous guide to everything there is to see and do on the island. Best-selling author and longtime Hawai''i resident, Andrew Doughty, unlocks the secrets of an island so lush and diverse that many visitors never realize all that it has to offer. Explore with him as he reveals breathtaking trails, secluded beaches, pristine reefs, delicious places to eat, colorful craters, hidden waterfalls and so much more. Every restaurant, activity provider, business and resort is reviewed personally and anonymously. This book and a rental car are all you need to discover what makes Maui so exciting.', 'https://www.amazon.com/gp/product/0996131809/ref=s9_acsd_top_hd_bw_b4Tr_c_x_4_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-6&pf_rd_r=ADJ0BD61PEAW285C5TAF&pf_rd_t=101&pf_rd_p=a1319b60-bc1c-5655-92b2-70a29978ae11&pf_rd_i=17227'),
(3, 'Jack''s Journey USA: One dog''s journey to inspire YOUR life of adventure!', 2016, 'Dawn Celapino', 'Travel', 'Have you ever had a dream to do something but didn''t know how you would ever do it? Read how one little dog inspired his mom to not only live out a dream but change the course of her life! It started with a dog fitness company and turned into an adventurous journey around the USA. All so she could spend more time with Jack. Dawn and her 10 year old Cairn Terrier, Jack, are a team. Together they traveled to 25 states, over 10,000 miles in 10 weeks in their custom RV named Spirit. Just a gal and her dog living life! They hiked, paddle boarded, met new friends, taught dog fitness classes and just had FUN! Join them on their journey and allow them to INSPIRE you to travel in this beautiful country, live your dreams and try new activities..with your DOG! They will help you with travel and dog tips and Jack will even give you his commentary on what "really" happened! Sit back and get ready to be entertained, educated and INSPIRED!', 'https://www.amazon.com/gp/product/0692689621/ref=s9_acsd_topr_hd_bw_b4Tr_c_x_1_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-10&pf_rd_r=ADJ0BD61PEAW285C5TAF&pf_rd_r=ADJ0BD61PEAW285C5TAF&pf_rd_t=101&pf_rd_p=0d8d0ae6-4736-4c88-9206-f7450228baf5&pf_rd_p=0d8d0ae6-4736-4c88-9206-f7450228baf5&pf_rd_i=17227'),
(4, 'Ancient Landscapes of the Colorado Platea', 2008, 'Ron Blakey, Wayne Ranney', 'Travel', 'Imagine seeing the varied landscapes of the earth as they used to look throughout hundreds of millions of years of earth history. Tropical seas lap on the shores of an Arizona beach. Immense sand dunes shift and swirl in Sahara-like deserts in Utah and New Mexico. Ancient rivers spill from a mountain range in Colorado that was a precursor to the modern Rockies. Such flights of geologic fancy are now tangible through the thought-provoking and beautiful paleogeographic maps, reminiscent of the maps in world atlases we all paged through as children, of Ancient Landscapes of the Colorado Plateau. Ron Blakey of Northern Arizona University is one of the world’s foremost authorities on the geologic history of the Colorado Plateau. For more than fifteen years, he has meticulously created maps that show how numerous past landscapes gave rise to the region’s stunning geologic formations. Ancient Landscapes of the Colorado Plateau is the first book to showcase Blakey’s remarkable work. His maps are accompanied by text by Wayne Ranney, geologist and award-winning author of Carving Grand Canyon. Ranney takes readers on a fascinating tour of the many landscapes depicted in the maps, and Blakey and Ranney’s fruitful collaboration brings the past alive like never before', 'https://www.amazon.com/gp/product/1934656038/ref=s9_acsd_topr_hd_bw_b4Tr_c_x_7_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-10&pf_rd_r=ADJ0BD61PEAW285C5TAF&pf_rd_r=ADJ0BD61PEAW285C5TAF&pf_rd_t=101&pf_rd_p=0d8d0ae6-4736-4c88-9206-f7450228baf5&pf_rd_p=0d8d0ae6-4736-4c88-9206-f7450228baf5&pf_rd_i=17227'),
(5, 'AWOL on the Appalachian Trail', 2010, 'David Miller', 'Travel', 'In 2003, software engineer David Miller left his job, family, and friends to fulfill a dream and hike the Appalachian Trail. AWOL on the Appalachian Trail is Miller''s account of this thru-hike along the entire 2,172 miles from Georgia to Maine. On page after page, readers are treated to rich descriptions of the valleys and mountains, the isolation and reverie, the inspiration that fueled his quest, and the life-changing moments that can only be experienced when dreams are pursued. While this book abounds with introspection and perseverance, it also provides useful passages about safety and proper gear, with a view into a professional hiker''s preparations and tenacity. This is not merely a travel guide, but a beautifully written and highly personal view into one man''s adventure and what it means to make a lifelong vision come true.', 'https://www.amazon.com/gp/product/B003JMFKRE/ref=s9_acsd_top_hd_bw_bQ_c_x_1_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-5&pf_rd_r=21EN1CY5AD1N7WNG8QB1&pf_rd_t=101&pf_rd_p=eb0d6cb9-343d-5df0-89a8-a1a3c8ab37b1&pf_rd_i=26'),
(6, 'Baseball Prospectus 2017', 2017, 'Baseball Prospectus', 'Sports', 'The 2017 edition of The New York Times Bestselling Guide.\n The 22nd edition of this industry-leading baseball annual contains all of the important regular and advanced statistics, player predictions and insider-level commentary that readers have come to expect, along with significant improvements to several statistics that were created by, and are exclusive to, Baseball Prospectus.', 'https://www.amazon.com/gp/product/1681626403/ref=s9_acsd_top_hd_bw_bQ_c_x_3_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-5&pf_rd_r=21EN1CY5AD1N7WNG8QB1&pf_rd_t=101&pf_rd_p=eb0d6cb9-343d-5df0-89a8-a1a3c8ab37b1&pf_rd_i=26'),
(7, '1984', 1949, 'George Orwell', 'Sci Fi', 'In 1984, London is a grim city where Big Brother is always watching you and the Thought Police can practically read your mind. Winston is a man in grave danger for the simple reason that his memory still functions. Drawn into a forbidden love affair, Winston finds the courage to join a secret revolutionary organization called The Brotherhood, dedicated to the destruction of the Party. Together with his beloved Julia, he hazards his life in a deadly match against the powers that be.', 'https://www.amazon.com/gp/product/B003JTHWKU/ref=s9_acsd_top_hd_bw_bP_c_x_1_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-8&pf_rd_r=9TV4RATZX856JGE6W3E8&pf_rd_t=101&pf_rd_p=3ec7f6b0-de0f-529b-be12-8640438c73ff&pf_rd_i=25'),
(8, 'Extracted', 2017, 'RR Haywood', 'Sci Fi', 'In 2061, a young scientist invents a time machine to fix a tragedy in his past. But his good intentions turn catastrophic when an early test reveals something unexpected: the end of the world.\r\n\r\nA desperate plan is formed. Recruit three heroes, ordinary humans capable of extraordinary things, and change the future.\r\n\r\nSafa Patel is an elite police officer, on duty when Downing Street comes under terrorist attack. As armed men storm through the breach, she dispatches them all.\r\n\r\n''Mad'' Harry Madden is a legend of the Second World War. Not only did he complete an impossible mission—to plant charges on a heavily defended submarine base—but he also escaped with his life.\r\n\r\nBen Ryder is just an insurance investigator. But as a young man he witnessed a gang assaulting a woman and her child. He went to their rescue, and killed all five.\r\n\r\nCan these three heroes, extracted from their timelines at the point of death, save the world?', 'https://www.amazon.com/gp/product/B01HIKCA52/ref=s9_acsd_top_hd_bw_bP_c_x_2_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-8&pf_rd_r=9TV4RATZX856JGE6W3E8&pf_rd_t=101&pf_rd_p=3ec7f6b0-de0f-529b-be12-8640438c73ff&pf_rd_i=25'),
(9, 'The Handmaid''s Tale', 1985, 'Margaret Atwood', 'Sci Fi', 'The Handmaid''s Tale is not only a radical and brilliant departure for Margaret Atwood, it is a novel of such power that the reader will be unable to forget its images and its forecast. Set in the near future, it describes life in what was once the United States, now called the Republic of Gilead, a monotheocracy that has reacted to social unrest and a sharply declining birthrate by reverting to, and going beyond, the repressive intolerance of the original Puritans. The regime takes the Book of Genesis absolutely at its word, with bizarre consequences for the women and men of its population.\r\nThe story is told through the eyes of Offred, one of the unfortunate Handmaids under the new social order. In condensed but eloquent prose, by turns cool-eyed, tender, despairing, passionate, and wry, she reveals to us the dark corners behind the establishment''s calm facade, as certain tendencies now in existence are carried to their logical conclusions. The Handmaid''s Tale is funny, unexpected, horrifying, and altogether convincing. It is at once scathing satire, dire warning, and tour de force. It is Margaret Atwood at her best.', 'https://www.amazon.com/gp/product/B003JFJHTS/ref=s9_acsd_top_hd_bw_bP_c_x_3_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-8&pf_rd_r=9TV4RATZX856JGE6W3E8&pf_rd_t=101&pf_rd_p=3ec7f6b0-de0f-529b-be12-8640438c73ff&pf_rd_i=25'),
(10, 'Norse Mythology', 2017, 'Neil Gaiman', 'Sci Fi', 'Introducing an instant classic―master storyteller Neil Gaiman presents a dazzling version of the great Norse myths.\r\n\r\nNeil Gaiman has long been inspired by ancient mythology in creating the fantastical realms of his fiction. Now he turns his attention back to the source, presenting a bravura rendition of the great northern tales.\r\n\r\nIn Norse Mythology, Gaiman stays true to the myths in envisioning the major Norse pantheon: Odin, the highest of the high, wise, daring, and cunning; Thor, Odin’s son, incredibly strong yet not the wisest of gods; and Loki―son of a giant―blood brother to Odin and a trickster and unsurpassable manipulator.', 'https://www.amazon.com/gp/product/039360909X/ref=s9_acsd_top_hd_bw_bP_c_x_4_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-8&pf_rd_r=9TV4RATZX856JGE6W3E8&pf_rd_t=101&pf_rd_p=3ec7f6b0-de0f-529b-be12-8640438c73ff&pf_rd_i=25'),
(11, 'Barbarian''s Redemption', 2017, 'Ruby Dixon', 'Sci Fi', 'For seasons, I have waited for her - my perfect mate.\r\n\r\nIn a tribe full of happy couples, I am alone. But I am not content to remain this way. There are no eligible unmated females left, so I will do whatever it takes to bring females back to our tribe...even if it means doing something wrong. Even if it means I must purchase my mate on the intergalactic black market. I will do anything to possess her, to claim her as my own\r\n.\r\nBut will my ruthless move turn my female against me before we ever meet? Can she ever forgive a male that bought her freedom?', 'https://www.amazon.com/gp/product/B01N6ZKJQZ/ref=s9_acsd_top_hd_bw_bP_c_x_5_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-8&pf_rd_r=9TV4RATZX856JGE6W3E8&pf_rd_t=101&pf_rd_p=3ec7f6b0-de0f-529b-be12-8640438c73ff&pf_rd_i=25'),
(12, 'The Winter Over', 2017, 'Matthew Iden', 'Sci Fi', 'Each winter the crew at the Shackleton South Pole Research Facility faces nine months of isolation, round-the-clock darkness, and one of the most extreme climates on the planet. For thirty-something mechanical engineer Cass Jennings, Antarctica offers an opportunity to finally escape the guilt of her troubled past and to rebuild her life.', 'https://www.amazon.com/gp/product/B01KI00WZE/ref=s9_acsd_newrz_hd_bw_bP_c_x_2_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-11&pf_rd_r=9TV4RATZX856JGE6W3E8&pf_rd_t=101&pf_rd_p=3ec7f6b0-de0f-529b-be12-8640438c73ff&pf_rd_i=25'),
(13, 'One Right Thing', 2013, 'Matthew Iden', 'Sci Fi', 'Retired DC Homicide detective Marty Singer is driving through rural Virginia when he sees a billboard by the side of the road with the picture of a man and a simple, stunning question:\r\n\r\nJ.D. HOPE WAS MURDERED ON MAY 6TH. DO YOU KNOW WHY?\r\n\r\nTo most, the message means nothing. But Marty stops the car, turns around, and rushes headlong into a deadly mix of drugs, lies, and double-crosses.', 'https://www.amazon.com/Right-Thing-Marty-Singer-Mystery-ebook/dp/B00PHZKMIS/ref=asap_bc?ie=UTF8'),
(14, 'The Odds of Loving Grover Cleveland', 2016, 'Rebekah Crane', 'Romance', 'According to sixteen-year-old Zander Osborne, nowhere is an actual place—and she’s just fine there. But her parents insist that she get out of her head—and her home state—and attend Camp Padua, a summer camp for at-risk teens.\r\n\r\nZander does not fit in—or so she thinks. She has only one word for her fellow campers: crazy. In fact, the whole camp population exists somewhere between disaster and diagnosis. There’s her cabinmate Cassie, a self-described manic-depressive-bipolar-anorexic. Grover Cleveland (yes, like the president), a cute but confrontational boy who expects to be schizophrenic someday, odds being what they are. And Bek, a charmingly confounding pathological liar.', 'https://www.amazon.com/gp/product/1503939820/ref=s9_acsd_cdx_hd_bw_b3TO_c_x_1_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-3&pf_rd_r=FKR5Z0YK9EK0NWSXAE8E&pf_rd_t=101&pf_rd_p=0bbc7b03-69a9-5ec0-924c-ee9f397b7ac0&pf_rd_i=13354'),
(15, 'Shining Sea', 2016, 'Mimi Cross', 'Romance', 'Seventeen-year-old Arion Rush has always played the obedient sidekick to her older sister’s flashy femme fatale—until a mysterious boating accident leaves Lilah a silent, traumatized stranger. As her sister awaits medical treatment with their mother, Arion and their father head to his hometown in Maine to prepare a new life for them all. Surrounded by the vast Atlantic, songwriting is Arion’s only solace, her solid ground.\r\n\r\nUnexpectedly, Arion blossoms in the tiny coastal town. Friends flock to her, and Logan Delaine, a volatile heartthrob, seems downright smitten. But it’s Bo Summers—a solitary surfer, as alluring as he is aloof—that Arion can’t shake. Meanwhile, Lilah’s worsening condition, a string of local fatalities, and Arion’s own recent brushes with death seem ominously linked…to Bo’s otherworldly family. As Arion’s feelings for Bo intensify and his affections turn possessive, she must make a choice. How will Arion learn to listen to her own voice when Bo’s siren song won’t stop ringing in her ears?', 'https://www.amazon.com/gp/product/1503935531/ref=s9_acsd_cdx_hd_bw_b3TO_c_x_5_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-3&pf_rd_r=FKR5Z0YK9EK0NWSXAE8E&pf_rd_t=101&pf_rd_p=0bbc7b03-69a9-5ec0-924c-ee9f397b7ac0&pf_rd_i=13354'),
(16, 'All the Breaking Waves: A Novel', 2016, 'Kerry Lonsdale', 'Romance', 'From the bestselling author of Everything We Keep comes a gripping tale of long-buried secrets, the strength of forgiveness, and the healing power of returning home for good.\r\n\r\nAfter a harrowing accident tore her family apart, Molly Brennan fled from the man she loved and the tragic mistake she made.\r\n\r\nTwelve years later, Molly has created a new life for herself and her eight-year-old daughter, Cassie. The art history professor crafts jewelry as unique and weathered as the surf-tumbled sea glass she collects, while raising her daughter in a safe and loving environment—something Molly never had. But when Cassie is plagued by horrific visions and debilitating nightmares, Molly is forced to return to the one place she swore she’d never move back to—home to Pacific Grove.', 'https://www.amazon.com/gp/product/1503941833/ref=s9_acsd_cdeal_hd_bw_b3TO_c_x_2_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-5&pf_rd_r=FKR5Z0YK9EK0NWSXAE8E&pf_rd_t=101&pf_rd_p=0bbc7b03-69a9-5ec0-924c-ee9f397b7ac0&pf_rd_i=13354'),
(17, 'Everything We Left Behind', 2015, 'Kerry Lonsdale', 'Romance', 'From the Wall Street Journal bestselling author of Everything We Keep comes the highly anticipated sequel. Told from one man’s two perspectives, Everything We Left Behind effortlessly blends suspense, mystery, and romance in an exploration of loss, resilience, and the compelling need to protect the ones we love at all cost.', 'https://www.amazon.com/Everything-We-Left-Behind-Novel-ebook/dp/B01N5FBTVO/ref=asap_bc?ie=UTF8'),
(18, 'Jesus Calling: Enjoying Peace in His Presence', 2004, 'Sarah Young', 'Spirituality', 'Uniquely inspired treasures from heaven for every day of the year by missionary Sarah Young.\r\n\r\nJesus Calling is a devotional filled with uniquely inspired treasures from heaven for every day of the year.  After many years of writing in her prayer journal, missionary Sarah Young decided to listen to God with pen in hand, writing down whatever she believed He was saying to her.  It was awkward at first, but gradually her journaling changed from monologue to dialogue.  She knew her writings were not inspired as Scripture is, but journaling helped her grow closer to God.  Others were blessed as she shared her writings, until people all over the world were using her messages.  They are written from Jesus'' point of view, thus the title Jesus Calling.  It is Sarah''s fervent prayer that our Savior may bless readers with His presence and His peace in ever deeper measure.', 'https://www.amazon.com/Jesus-Calling-Enjoying-Peace-Presence/dp/1591451884/ref=sr_1_1?s=books&ie=UTF8&qid=1486577749&sr=1-1'),
(19, 'The 5 Love Languages: The Secret to Love that Lasts', 2015, 'Gary Chapman', 'Spirituality', 'Falling in love is easy. Staying in love—that’s the challenge. How can you keep your relationship fresh and growing amid the demands, conflicts, and just plain boredom of everyday life?\r\n\r\nIn the #1 New York Times bestseller The 5 Love Languages, you’ll discover the secret that has transformed millions of relationships worldwide. Whether your relationship is flourishing or failing, Dr. Gary Chapman’s proven approach to showing and receiving love will help you experience deeper and richer levels of intimacy with your partner—starting today.\r\n\r\nThe 5 Love Languages is as practical as it is insightful. Updated to reflect the complexities of relationships today, this new edition reveals intrinsic truths and applies relevant, actionable wisdom in ways that work.\r\n\r\nIncludes the Couple''s Personal Profile assessment so you can discover your love language and that of your loved one.', 'https://www.amazon.com/Love-Languages-Secret-that-Lasts/dp/080241270X/ref=sr_1_5?s=books&ie=UTF8&qid=1486577749&sr=1-5'),
(20, 'The Four Agreements: A Practical Guide to Personal Freedom', 1997, 'Don Miguel Ruiz', 'Philosophy', 'In The Four Agreements, bestselling author don Miguel Ruiz reveals the source of self-limiting beliefs that rob us of joy and create needless suffering. Based on ancient Toltec wisdom, The Four Agreements offer a powerful code of conduct that can rapidly transform our lives to a new experience of freedom, true happiness, and love.\r\n\r\n• A New York Times bestseller for over 8 years\r\n• Over 6 million copies sold in the U.S.\r\n• Translated into 40 languages worldwide', 'https://www.amazon.com/gp/product/1878424319/ref=s9_acsd_top_hd_bw_b2rj_c_x_1_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-4&pf_rd_r=1225E66XZH0CPM0B68FD&pf_rd_t=101&pf_rd_p=50151b4b-240f-5bf9-b471-8130c84ae385&pf_rd_i=11019'),
(21, 'Out of My Later Years: Albert Einstein', 1950, 'Albert Einstein', 'Philosophy', 'Divided by subject matter—“Science,” “Convictions and Beliefs,” “Public Affairs,” etc.—these essays consider everything from the need for a “supranational” governing body to control war in the atomic age to freedom in research and education to Jewish history and Zionism to explanations of the physics and scientific thought that brought Albert Einstein world recognition. Throughout, Einstein’s clear, eloquent voice presents an idealist’s vision and relays complex theories to the layperson.', 'https://www.amazon.com/gp/product/B004Q9U0L0/ref=s9_acsd_top_hd_bw_b2rj_c_x_3_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-4&pf_rd_r=1225E66XZH0CPM0B68FD&pf_rd_t=101&pf_rd_p=50151b4b-240f-5bf9-b471-8130c84ae385&pf_rd_i=11019'),
(22, 'Elon Musk and the Quest for a Fantastic Future', 2017, 'Ashlee Vance', 'Philosophy', 'This fascinating and easily accessible young readers’ adaptation of Ashlee Vance’s New York Times bestselling Elon Musk: Tesla, SpaceX, and the Quest for a Fantastic Future features black-and-white photographs throughout and an epilogue. The version for adults has been praised as “riveting” (The Financial Times), “spirited” (The Wall Street Journal), and “masterful” (Vice). Now younger readers can read about this innovative leader who is revolutionizing three industries at once: space, automotive, and energy.', 'https://www.amazon.com/Quest-Fantastic-Future-Young-Readers/dp/0062463276/ref=sr_1_2?s=books&ie=UTF8&qid=1486578149&sr=1-2'),
(23, 'The Art of Happiness', 2009, 'Dalai Lama', 'Philosophy', 'Nearly every time you see him, he''s laughing, or at least smiling. And he makes everyone else around him feel like smiling. He''s the Dalai Lama, the spiritual and temporal leader of Tibet, a Nobel Prize winner, and a hugely sought-after speaker and statesman. Why is he so popular? Even after spending only a few minutes in his presence you can''t help feeling happier.', 'https://www.amazon.com/Art-Happiness-10th-Anniversary-Handbook/dp/1594488894/ref=sr_1_2?s=books&ie=UTF8&qid=1486578259&sr=1-2'),
(24, 'Dangerous', 2017, 'Milo Yiannopoulos', 'Politics', 'A new book by Milo Yiannopoulos entitled Dangerous published by Threshold Editions. Coming out soon.', 'https://www.amazon.com/gp/product/1501173081/ref=s9_acsd_top_hd_bw_b652Pvn_c_x_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-4&pf_rd_r=AJESBPNNZS9WVF5RXE8Y&pf_rd_t=101&pf_rd_p=39896b55-86d0-5c90-a1de-080985d47864&pf_rd_i=5571255011'),
(25, 'Big Agenda: President Trump’s Plan to Save America', 2017, 'David Horowitz', 'Politics', 'Donald Trump’s victory in the 2016 election was more than a historic upset. It was the beginning of a major political, economic, and social revolution that will change America — and the world.\r\n\r\nOne of the nation’s foremost conservative commentators, New York Times bestselling author, and a mentor to many of Donald Trump’s key advisers, David Horowitz presents a White House battle plan to halt the Democrats’ march to extinguish the values America holds dear.', 'https://www.amazon.com/gp/product/1630060879/ref=s9_acsd_top_hd_bw_b652Pvn_c_x_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-4&pf_rd_r=AJESBPNNZS9WVF5RXE8Y&pf_rd_t=101&pf_rd_p=39896b55-86d0-5c90-a1de-080985d47864&pf_rd_i=5571255011'),
(26, 'Black Edge', 2017, 'Sheelah Kolhatkar', 'Politics', 'The story of the billionaire trader Steven A. Cohen, the rise and fall of his hedge fund, SAC Capital, and the largest insider trading investigation in history—for readers of The Big Short, Den of Thieves, and Dark Money.\r\n\r\nThe rise over the last two decades of a powerful new class of billionaire financiers marks a singular shift in the American economic and political landscape. Their vast reserves of concentrated wealth have allowed a small group of big winners to write their own rules of capitalism and public policy. How did we get here? Through meticulous reporting and powerful storytelling, New Yorker staff writer Sheelah Kolhatkar shows how Steve Cohen became one of the richest and most influential figures in finance—and what happened when the Justice Department put him in its crosshairs.', 'https://www.amazon.com/gp/product/0812995805/ref=s9_acsd_top_hd_bw_b652Pvn_c_x_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-4&pf_rd_r=AJESBPNNZS9WVF5RXE8Y&pf_rd_t=101&pf_rd_p=39896b55-86d0-5c90-a1de-080985d47864&pf_rd_i=5571255011'),
(27, 'Echoes in Death', 2017, 'J.D. Robb', 'Mystery', 'Echoes in Death, the chilling new suspense novel from #1 New York Times bestselling author J.D. Robb is the perfect entry point into the compelling In Death police procedural series featuring Lieutenant Eve Dallas.\r\n\r\nAs NY Lt. Eve Dallas and her billionaire husband Roarke are driving home, a young woman—dazed, naked, and bloody—suddenly stumbles out in front of their car. Roarke slams on the brakes and Eve springs into action.', 'https://www.amazon.com/gp/product/B01GNYVS52/ref=s9_acsd_top_hd_bw_bI_c_x_1_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-10&pf_rd_r=3AGZBQNHSJEQPYX0MDH4&pf_rd_t=101&pf_rd_p=1899578c-9415-51f5-a7de-6e9536059cfa&pf_rd_i=18'),
(28, 'And Then She Was GONE', 2016, 'Christopher Greyson', 'Mystery', 'What’s done in the dark will be brought to the light…\r\n\r\nThe silhouette stood at the edge of the woods like a spider watching a fly enter its carefully crafted web. Only a few more steps and she’d be within its grasp.\r\n\r\nStacy Shaw has her whole life ahead of her. New job, new house and now a baby on the way—everything she’s ever hoped for is finally coming true. But on a warm summer night on the way home from work, she vanishes. The police race to find her, but the clues don’t add up. Conflicting facts emerge as her story twists and turns, sending the trail spiraling in all directions.', 'https://www.amazon.com/gp/product/B01K227MX8/ref=s9_acsd_top_hd_bw_bI_c_x_4_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-10&pf_rd_r=3AGZBQNHSJEQPYX0MDH4&pf_rd_t=101&pf_rd_p=1899578c-9415-51f5-a7de-6e9536059cfa&pf_rd_i=18'),
(29, 'The Shack', 2007, 'William P. Young', 'Mystery', 'Mackenzie Allen Phillips''s youngest daughter, Missy, has been abducted during a family vacation, and evidence that she may have been brutally murdered is found in an abandoned shack deep in the Oregon wilderness. Four years later, in this midst of his great sadness, Mack receives a suspicious note, apparently from God, inviting him back to that shack for a weekend. Against his better judgment he arrives at the shack on wintry afternoon and walks back into his darkest nightmare. What he finds there will change his life forever.', 'https://www.amazon.com/gp/product/B001B8Z2S0/ref=s9_acsd_top_hd_bw_bI_c_x_6_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-10&pf_rd_r=3AGZBQNHSJEQPYX0MDH4&pf_rd_t=101&pf_rd_p=1899578c-9415-51f5-a7de-6e9536059cfa&pf_rd_i=18'),
(30, 'Eve', 2015, 'Wm. Paul Young', 'Mystery', 'From the author of the twenty-five-million-copy bestseller The Shack comes a captivating new novel destined to be one of the most talked-about books of the decade.\r\n\r\nEve is a bold, unprecedented exploration of the Creation narrative, true to the original texts and centuries of scholarship—yet with breathtaking discoveries that challenge traditional beliefs about who we are and how we’re made. Eve opens a refreshing conversation about the equality of men and women within the context of our beginnings, helping us see each other as our Creator does—complete, unique, and not constrained by cultural rules or limitations.', 'https://www.amazon.com/Eve-Novel-Wm-Paul-Young-ebook/dp/B00SDPKAKE/ref=pd_sim_351_2?_encoding=UTF8&psc=1&refRID=Z3BBCAKCFK6RPF1N67Q7'),
(31, 'Cross Roads', 2012, 'Wm Paul Young', 'Mystery', '<p>Multi-millionaire Anthony Spencer is trapped in a coma and finds himself in a surreal world that reflects the skewed priorities of the life he''s lived on earth where he meets a stranger who turns out to be Jesus and a grandmother who is the Holy Spirit.</p><p>Pleading for a second chance, he is sent back to earth to redeem himself. There he must fight to put right the mess he''s created, experiencing events through others'' eyes before deciding how to use the miraculous gift he''s been given. Before his illness he had set events in motion that he now needs to undo - but will he have the courage to make the right choice?</p><p>THE SHACK is an international phenomenon, surpassing 1 million copies sold before being picked up by a mainstream publisher: its combination of radical spirituality with a heart-wrenching story made it a word-of-mouth hit, and CROSS ROADS has all the ingredients to repeat its impact.</p>', 'https://www.amazon.com/Cross-Roads-could-things-right-ebook/dp/B008HTPX3K/ref=sr_1_5?s=digital-text&ie=UTF8&qid=1486578986&sr=1-5'),
(32, 'Mindset: The New Psychology of Success', 2007, 'Carol S. Dweck', 'Law', 'World-renowned Stanford University psychologist Carol Dweck, in decades of research on achievement and success, has discovered a truly groundbreaking idea–the power of our mindset.\r\n\r\nDweck explains why it’s not just our abilities and talent that bring us success–but whether we approach them with a fixed or growth mindset. She makes clear why praising intelligence and ability doesn’t foster self-esteem and lead to accomplishment, but may actually jeopardize success. With the right mindset, we can motivate our kids and help them to raise their grades, as well as reach our own goals–personal and professional. Dweck reveals what all great parents, teachers, CEOs, and athletes already know: how a simple idea about the brain can create a love of learning and a resilience that is the basis of great accomplishment in every area.\r\n', 'https://www.amazon.com/gp/product/0345472322/ref=s9_acsd_top_hd_bw_b2np_c_x_1_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-11&pf_rd_r=GTMAF9T09384PTQGQWPW&pf_rd_t=101&pf_rd_p=e3044e41-cb7a-51dc-8b02-9edfa56b5139&pf_rd_i=10777'),
(33, 'The New Jim Crow: Mass Incarceration in the Age of Colorblindness', 2012, 'Michelle Alexander', 'Law', 'Once in a great while a book comes along that changes the way we see the world and helps to fuel a nationwide social movement. The New Jim Crow is such a book. Praised by Harvard Law professor Lani Guinier as "brave and bold," this book directly challenges the notion that the election of Barack Obama signals a new era of colorblindness. With dazzling candor, legal scholar Michelle Alexander argues that "we have not ended racial caste in America; we have merely redesigned it." By targeting black men through the War on Drugs and decimating communities of color, the U.S. criminal justice system functions as a contemporary system of racial control—relegating millions to a permanent second-class status—even as it formally adheres to the principle of colorblindness. In the words of Benjamin Todd Jealous, president and CEO of the NAACP, this book is a "call to action."', 'https://www.amazon.com/gp/product/1595586431/ref=s9_acsd_top_hd_bw_b2np_c_x_2_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-11&pf_rd_r=GTMAF9T09384PTQGQWPW&pf_rd_t=101&pf_rd_p=e3044e41-cb7a-51dc-8b02-9edfa56b5139&pf_rd_i=10777'),
(34, 'How to Debate Leftists and Destroy Them', 2014, 'Ben Shapiro', 'Law', 'The problem, as Ben Shapiro puts it in this must-read, is that “because conservatives don’t think about how to win that they constantly lose” in confrontations with leftists. The solution is to stop taking the bullying and learning to argue for victory.\r\nAmong Shapiro’s rules for beating the left in confrontations are: \r\nBe willing to take a punch. (conservatives tend to shy away from confrontations because the left is rhetorically violent; but it is important “to walk toward the fire.” ) \r\nHit hard, hit first. (leftists stage muggings; instead of fighting by Marquis of Queensberry rules, conservatives need to accept the strategy Mike Tyson: “Everybody has a plan until they get punched in the mouth.”)', 'https://www.amazon.com/gp/product/B00JRJQ7Z2/ref=s9_acsd_top_hd_bw_b2np_c_x_5_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-11&pf_rd_r=GTMAF9T09384PTQGQWPW&pf_rd_t=101&pf_rd_p=e3044e41-cb7a-51dc-8b02-9edfa56b5139&pf_rd_i=10777'),
(35, 'Toddlers Are A**holes: It''s Not Your Fault', 2015, 'Bunmi Laditan', 'Humour', 'Toddler a**holery is a normal part of human development—not unlike puberty, except this stage involves throwing food on the floor and taking swings at people who pay your way in life. For parents of toddlers, it''s a "you better laugh so you don''t cry" period.', 'https://www.amazon.com/gp/product/B00SM1214C/ref=s9_acsd_top_hd_bw_b19s_c_x_3_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-10&pf_rd_r=NZY78EGNZ6ETBQ849M5J&pf_rd_r=NZY78EGNZ6ETBQ849M5J&pf_rd_t=101&pf_rd_p=c18ecee7-60af-4979-adff-d0f0bfafc6cb&pf_rd_p=c18ecee7-60af-4979-adff-d0f0bfafc6cb&pf_rd_i=4456'),
(36, 'Better Off Without Him', 2013, 'Dee Ernst', 'Humour', 'Mona Berman has it all—a twenty-year marriage, a successful career as a romance novelist, and three teenage daughters. But when her husband, Brian, leaves her for someone younger, thinner, blonde, and French, she has to step back and take a good, long look at her life.\r\nFirst, her career. She can’t continue to write about “Happily Ever After,” so she changes the heroine of her new book from a hot young thing to a forty-something woman who manages to find happiness without a man. Her agent isn’t too happy—the heroine is how old? She doesn’t get the guy in the end? How is that even possible?', 'https://www.amazon.com/gp/product/B00CFQOG84/ref=s9_acsd_top_hd_bw_b19w_c_x_3_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-4&pf_rd_r=DXEBCK3MM07SHG7BNMGW&pf_rd_t=101&pf_rd_p=52c1d2de-2264-50b7-bee6-6922170b4edf&pf_rd_i=4460'),
(37, 'The Trans Am Diaries', 2014, 'Steven Dupin', 'Humour', 'Stevie D. thought he had made it. After leaving his small-town Kentucky home for the bright lights of Hollywood, this self-described "white trash hillbilly" rose through the stand-up comedy ranks to become a star on the Sunset Strip. Since the release of his successful concert-film DVD, Rockstars of Comedy, Stevie began developing projects with rock legend Tommy Lee, UFC Champion Rich Franklin, Hot Rod Builder of the Year Troy Ladd and other celebrities. With a beautiful wife, he was also enjoying the greatest adventure of his life -fatherhood.', 'https://www.amazon.com/gp/product/0938467905/ref=s9_acsd_topr_hd_bw_b19w_c_x_2_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-7&pf_rd_r=DXEBCK3MM07SHG7BNMGW&pf_rd_t=101&pf_rd_p=52c1d2de-2264-50b7-bee6-6922170b4edf&pf_rd_i=4460'),
(38, 'HTML and CSS: Design and Build Websites', 2011, 'Jon Duckett', 'Programming', 'A full-color introduction to the basics of HTML and CSS from the publishers of Wrox! \r\nEvery day, more and more people want to learn some HTML and CSS. Joining the professional web designers and programmers are new audiences who need to know a little bit of code at work (update a content management system or e-commerce store) and those who want to make their personal blogs more attractive. Many books teaching HTML and CSS are dry and only written for those who want to become programmers, which is why this book takes an entirely new approach.', 'https://www.amazon.com/gp/product/1118008189/ref=s9_acsd_top_hd_bw_bzv_c_x_2_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-3&pf_rd_r=NQG5A9M0RYVQDVW5Q35Y&pf_rd_r=NQG5A9M0RYVQDVW5Q35Y&pf_rd_t=101&pf_rd_p=59030051-9707-4ee1-ab91-cca54ef037ab&pf_rd_p=59030051-9707-4ee1-ab91-cca54ef037ab&pf_rd_i=3839'),
(39, 'The Self-Taught Programmer: The Definitive Guide to Programming Professionally', 2016, 'Cory Althoff', 'Programming', 'I am a self-taught programmer. After a year of self-study, I learned to program well enough to land a job as a software engineer II at eBay. Once I got there, I realized I was severely under-prepared. I was overwhelmed by the amount of things I needed to know but hadn''t learned yet. My journey learning to program, and my experience at my first job as a software engineer were the inspiration for this book.', 'https://www.amazon.com/gp/product/B01M01YDQA/ref=s9_acsd_top_hd_bw_bzv_c_x_3_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-3&pf_rd_r=NQG5A9M0RYVQDVW5Q35Y&pf_rd_r=NQG5A9M0RYVQDVW5Q35Y&pf_rd_t=101&pf_rd_p=59030051-9707-4ee1-ab91-cca54ef037ab&pf_rd_p=59030051-9707-4ee1-ab91-cca54ef037ab&pf_rd_i=3839'),
(40, 'Python Crash Course: A Hands-On, Project-Based Introduction to Programming', 2015, 'Eric Matthes', 'Programming', 'Python Crash Course is a fast-paced, thorough introduction to programming with Python that will have you writing programs, solving problems, and making things that work in no time.\r\n\r\nIn the first half of the book, you''ll learn about basic programming concepts, such as lists, dictionaries, classes, and loops, and practice writing clean and readable code with exercises for each topic. You''ll also learn how to make your programs interactive and how to test your code safely before adding it to a project. In the second half of the book, you''ll put your new knowledge into practice with three substantial projects: a Space Invaders-inspired arcade game, data visualizations with Python''s super-handy libraries, and a simple web app you can deploy online.', 'https://www.amazon.com/gp/product/1593276036/ref=s9_acsd_top_hd_bw_bzv_c_x_4_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-3&pf_rd_r=NQG5A9M0RYVQDVW5Q35Y&pf_rd_r=NQG5A9M0RYVQDVW5Q35Y&pf_rd_t=101&pf_rd_p=59030051-9707-4ee1-ab91-cca54ef037ab&pf_rd_p=59030051-9707-4ee1-ab91-cca54ef037ab&pf_rd_i=3839'),
(41, 'SQL: The Ultimate Guide From Beginner To Expert', 2017, 'Peter Adams', 'Programming', 'Whether you’re a beginner or a professional developer, knowing your way around databases is essential. From airlines to hospitals and banks to retailers, nearly every organization relies on databases to run their businesses. SQL is the primary language for managing and interacting with those databases making it essential for database administrators, programmers, and many back-end developers.', 'https://www.amazon.com/gp/product/B01MSKSJ7H/ref=s9_acsd_top_hd_bw_bzv_c_x_5_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-3&pf_rd_r=NQG5A9M0RYVQDVW5Q35Y&pf_rd_r=NQG5A9M0RYVQDVW5Q35Y&pf_rd_t=101&pf_rd_p=59030051-9707-4ee1-ab91-cca54ef037ab&pf_rd_p=59030051-9707-4ee1-ab91-cca54ef037ab&pf_rd_i=3839'),
(42, 'Deadpool Kills the Marvel Universe', 2012, 'Cullen Bunn', 'Comics', 'What if everything you thought was funny about Deadpool was actually just disturbing? What if he decided to kill everyone and everything that makes up the Marvel Universe? What if he actually pulled it off? Would that be FUN for you? The Merc with a Mouth takes a turn for the twisted in a horror comic like no other! Collecting DEADPOOL KILLS THE MARVEL UNIVERSE #1-4.', 'https://www.amazon.com/gp/product/0785164030/ref=s9_acsd_top_hd_bw_b3d1nRr_c_x_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-3&pf_rd_r=8567MK2P0D7MSFP9AVPT&pf_rd_t=101&pf_rd_p=7d0f321c-120b-5676-8ecf-dc4dcb9299b0&pf_rd_i=3325104011'),
(43, 'Infinity Gauntlet', 2011, 'Jim Starlin', 'Comics', 'It''s the Avengers, the New Warriors, the X-Men and more against the omnipotent Eternal, Thanos! The Mad Titan has become the most powerful being in the universe, and enslavement or destruction may be the only choices he gives it! The successive Starlin sagas that shook space and time start here!', 'https://www.amazon.com/gp/product/0785156593/ref=s9_acsd_top_hd_bw_b3d1nRr_c_x_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-3&pf_rd_r=8567MK2P0D7MSFP9AVPT&pf_rd_t=101&pf_rd_p=7d0f321c-120b-5676-8ecf-dc4dcb9299b0&pf_rd_i=3325104011'),
(44, 'Justice League, Vol. 1: Origin', 2013, 'Geoff Johns', 'Comics', 'As a part of the monumental DC Comics—The New 52 event, comics superstars Geoff Johns and Jim Lee bring you an all-new origin story for the Justice League!\r\nIn a world where inexperienced superheroes operate under a cloud of suspicion from the public, loner vigilante Batman has stumbled upon a dark evil that threatens to destroy the earth as we know it. Now, faced with a threat far beyond anything he can handle on his own, the Dark Knight must trust an alien, a scarlet speedster, an accidental teenage hero, a space cop, an Amazon Princess and an undersea monarch. Will this combination of Superman, The Flash, Cyborg, Green Lantern, Wonder Woman and Aquaman be able to put aside their differences and come together to save the world? Or will they destroy each other first?', 'https://www.amazon.com/gp/product/1401237886/ref=s9_acsd_top_hd_bw_b3d1nRr_c_x_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-3&pf_rd_r=8567MK2P0D7MSFP9AVPT&pf_rd_t=101&pf_rd_p=7d0f321c-120b-5676-8ecf-dc4dcb9299b0&pf_rd_i=3325104011'),
(45, 'Civil War', 2007, 'Mark Millar', 'Comics', 'The landscape of the Marvel Universe is changing, and it''s time to choose: Whose side are you on? A conflict has been brewing from more than a year, threatening to pit friend against friend, brother against brother - and all it will take is a single misstep to cost thousands their lives and ignite the fuse.', 'https://www.amazon.com/gp/product/078512179X/ref=s9_acsd_top_hd_bw_b3d1nRr_c_x_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-3&pf_rd_r=8567MK2P0D7MSFP9AVPT&pf_rd_t=101&pf_rd_p=7d0f321c-120b-5676-8ecf-dc4dcb9299b0&pf_rd_i=3325104011'),
(46, 'The Flash: Rebirth', 2011, 'Geoff Johns', 'Comics', 'The epic story of Barry Allen’s return from the dead to reclaim his title as The Fastest Man Alive is collected in hardcover.\r\nGeoff Johns and Ethan Van Sciver, the writer/artist team behind the blockbuster GREEN LANTERN: REBIRTH and THE SINESTRO CORPS WAR, create an explosive, jaw-dropping epic that reintroduces Barry Allen, the modern–age Flash. But how will Barry Allen find his place in the twenty-first century?', 'https://www.amazon.com/gp/product/1401230016/ref=s9_acsd_top_hd_bw_b3d1nRr_c_x_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-3&pf_rd_r=8567MK2P0D7MSFP9AVPT&pf_rd_t=101&pf_rd_p=7d0f321c-120b-5676-8ecf-dc4dcb9299b0&pf_rd_i=3325104011'),
(47, 'The Catcher in the Rye', 1951, 'J.D. Salinger', 'Classic', 'Anyone who has read J.D. Salinger''s New Yorker stories ? particularly A Perfect Day for Bananafish, Uncle Wiggily in Connecticut, The Laughing Man, and For Esme ? With Love and Squalor, will not be surprised by the fact that his first novel is fully of children. The hero-narrator of THE CATCHER IN THE RYE is an ancient child of sixteen, a native New Yorker named Holden Caulfield. Through circumstances that tend to preclude adult, secondhand description, he leaves his prep school in Pennsylvania and goes underground in New York City for three days. The boy himself is at once too simple and too complex for us to make any final comment about him or his story. Perhaps the safest thing we can say about Holden is that he was born in the world not just strongly attracted to beauty but, almost, hopelessly impaled on it. There are many voices in this novel: children''s voices, adult voices, underground voices-but Holden''s voice is the most eloquent of all.', 'https://www.amazon.com/gp/product/0316769487/ref=s9_acsd_zwish_hd_bw_b2hj_c_x_3_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-6&pf_rd_r=BY24PGK46NS76WPR2M4A&pf_rd_t=101&pf_rd_p=a9154b24-42d4-592d-a0e9-b835d5e0f2c0&pf_rd_i=10399'),
(48, 'One Hundred Years of Solitude', 1967, 'Gabriel Garcia Marquez', 'Classic', 'One Hundred Years of Solitude tells the story of the rise and fall, birth and death of the mythical town of Macondo through the history of the Buendia family. Inventive, amusing, magnetic, sad, and alive with unforgettable men and women—brimming with truth, compassion, and a lyrical magic that strikes the soul—this novel is a masterpiece in the art of fiction.', 'https://www.amazon.com/gp/product/0060883286/ref=s9_acsd_zwish_hd_bw_b2hj_c_x_2_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-6&pf_rd_r=BY24PGK46NS76WPR2M4A&pf_rd_t=101&pf_rd_p=a9154b24-42d4-592d-a0e9-b835d5e0f2c0&pf_rd_i=10399'),
(49, 'Animal Farm', 1945, 'George Orwell', 'Classic', 'A farm is taken over by its overworked, mistreated animals. With flaming idealism and stirring slogans, they set out to create a paradise of progress, justice, and equality. Thus the stage is set for one of the most telling satiric fables ever penned—a razor-edged fairy tale for grown-ups that records the evolution from revolution against tyranny to a totalitarianism just as terrible. \r\n \r\nWhen Animal Farm was first published, Stalinist Russia was seen as its target. Today it is devastatingly clear that wherever and whenever freedom is attacked, under whatever banner, the cutting clarity and savage comedy of George Orwell’s masterpiece have a meaning and message still ferociously fresh.', 'https://www.amazon.com/gp/product/0451526341/ref=s9_acsd_zwish_hd_bw_b2hj_c_x_1_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-6&pf_rd_r=BY24PGK46NS76WPR2M4A&pf_rd_t=101&pf_rd_p=a9154b24-42d4-592d-a0e9-b835d5e0f2c0&pf_rd_i=10399'),
(50, 'The Little Prince', 1943, 'Antoine de Saint-Exupér', 'Classic', 'Few stories are as widely read and as universally cherished by children and adults alike as The Little Prince. Richard Howard''s translation of the beloved classic beautifully reflects Saint-Exupéry''s unique and gifted style. Howard, an acclaimed poet and one of the preeminent translators of our time, has excelled in bringing the English text as close as possible to the French, in language, style, and most important, spirit. The artwork in this edition has been restored to match in detail and in color Saint-Exupéry''s original artwork. Combining Richard Howard''s translation with restored original art, this definitive English-language edition of The Little Prince will capture the hearts of readers of all ages.', 'https://www.amazon.com/gp/product/0156012197/ref=s9_acsd_zgift_hd_bw_b2hj_c_x_1_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-11&pf_rd_r=BY24PGK46NS76WPR2M4A&pf_rd_t=101&pf_rd_p=a9154b24-42d4-592d-a0e9-b835d5e0f2c0&pf_rd_i=10399'),
(51, 'Grimm''s Complete Fairy Tales', 2011, 'Jacob Grimm, Wilhelm Grimm', 'Classic', 'They are the stories we''ve known since we were children. Rapunzel. Hansel and Gretel. Cinderella. Sleeping Beauty. But the works originally collected by the Brothers Grimm in the early 1800s are not necessarily the versions we heard before bedtime. They''re darker and often don''t end very happily—but they''re often far more interesting.\r\n\r\nThis elegant edition of Grimm''s Complete Fairy Tales includes all our cherished favorites—Snow White, Rumpelstiltskin, Little Red Cap, and many more—in their original versions. With specially designed end papers, a genuine leather cover, and other enhancements, it''s the perfect gift for anyone looking to build a complete home library.', 'https://www.amazon.com/gp/product/1607103133/ref=s9_acsd_zwish_hd_bw_b2hj_c_x_7_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-6&pf_rd_r=BY24PGK46NS76WPR2M4A&pf_rd_t=101&pf_rd_p=a9154b24-42d4-592d-a0e9-b835d5e0f2c0&pf_rd_i=10399'),
(52, 'Eat Happy', 2016, 'Anna Vocino', 'Cooking', 'Eat Happy has 154 delicious grain-free, gluten-free recipes that are also free of any processed sugars.  There are meats, fish, sides, soups, starters, casseroles, slow cooker recipes, breakfast dishes, and even desserts to satisfy any sweets craving you might have, all with virtually no sugar.  If you are low carb, paleo, are wanting to keep autoimmune issues at bay, or just want to lose extra weight, Eat Happy gives you comfort food where you won’t miss the sugars or grains so your body and brain can feel happy from eating real foods.', 'https://www.amazon.com/gp/product/1941536883/ref=s9_acsd_topr_hd_bw_b6_c_x_1_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-5&pf_rd_r=PKB1K95VKXEBNWCSRPWT&pf_rd_t=101&pf_rd_p=5b9ffbc6-6488-5a85-85bb-c8da14b84607&pf_rd_i=6'),
(53, 'Chasing the Heat: 50 Years and a Million Meals', 2014, 'Leonard Gentieu', 'Cooking', 'Experience a chef s fifty-year journey beginning as a dishwasher, on to the Army mess tents, through a day from hell at one of his successful restaurants, to his thriving charter dinner cruise business. An insider s exploration of the challenges and triumphs of a life in the kitchen told with humor, frankness, optimism, and his favorite recipes.', 'https://www.amazon.com/Chasing-Heat-Years-Million-Meals/dp/1631100696');
INSERT INTO `books` (`id`, `book_name`, `book_year`, `book_author`, `book_genre`, `book_synopsis`, `book_link`) VALUES
(54, 'Palestine on a Plate: Memories from My Mother''s Kitchen', 2016, 'Joudie Kalla', 'Cooking', 'Palestinian food is not just found on the streets with the ka''ak (sesame) bread sellers and stalls selling za''atar chicken and mana eesh (za''atar and sesame bread), but in the home too; in the kitchens all across the country, where families cook and eat together every day, in a way that generations before them have always done. Palestine on a Plate is a tribute to family, cooking, and home--old recipes created with love that brings people together in appreciation of the beauty of this rich heritage. Immerse yourself in the stories and culture of Palestine through the food in this book.', 'https://www.amazon.com/gp/product/1566560691/ref=s9_acsd_topr_hd_bw_b6_c_x_6_w?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-5&pf_rd_r=PKB1K95VKXEBNWCSRPWT&pf_rd_t=101&pf_rd_p=5b9ffbc6-6488-5a85-85bb-c8da14b84607&pf_rd_i=6');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
